CREATE DATABASE BookStore;

USE BookStore;
CREATE TABLE Books (
BookID INT PRIMARY KEY AUTO_INCREMENT,
BookName VARCHAR(100)
);
CREATE TABLE Orders (
OrderID INT PRIMARY KEY,
BookID INT,
FOREIGN KEY (BookID) REFERENCES Books(BookID)
);
ALTER TABLE Books
ADD COLUMN ISBN VARCHAR(20) UNIQUE;

DELETE FROM Orders
WHERE OrderID =1;

TRUNCATE TABLE Orders;